# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-06 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0004_target_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patchhistory",
            name="date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
