# Generated by Django 4.2.17 on 2024-12-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0005_history_dateindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfbotBranch',
            fields=[
                ('patch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cfbot_branch', serialize=False, to='commitfest.patch')),
                ('branch_id', models.IntegerField()),
                ('branch_name', models.TextField()),
                ('commit_id', models.TextField(blank=True, null=True)),
                ('apply_url', models.TextField()),
                ('status', models.TextField(choices=[('testing', 'Testing'), ('finished', 'Finished'), ('failed', 'Failed'), ('timeout', 'Timeout')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CfbotTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_id', models.TextField(unique=True)),
                ('task_name', models.TextField()),
                ('branch_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('status', models.TextField(choices=[('CREATED', 'Created'), ('NEEDS_APPROVAL', 'Needs Approval'), ('TRIGGERED', 'Triggered'), ('EXECUTING', 'Executing'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed'), ('SCHEDULED', 'Scheduled'), ('ABORTED', 'Aborted'), ('ERRORED', 'Errored')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfbot_tasks', to='commitfest.patch')),
            ],
        ),
        migrations.RunSQL(
            """
            CREATE TYPE cfbotbranch_status AS ENUM (
                'testing',
                'finished',
                'failed',
                'timeout'
            );
            """
        ),
        migrations.RunSQL(
            """
            CREATE TYPE cfbottask_status AS ENUM (
                'CREATED',
                'NEEDS_APPROVAL',
                'TRIGGERED',
                'EXECUTING',
                'FAILED',
                'COMPLETED',
                'SCHEDULED',
                'ABORTED',
                'ERRORED'
            );
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE commitfest_cfbotbranch
            ALTER COLUMN status TYPE cfbotbranch_status
            USING status::cfbotbranch_status;
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE commitfest_cfbottask
            ALTER COLUMN status TYPE cfbottask_status
            USING status::cfbottask_status;
            """
        ),
    ]
