# Generated by Django 4.2.17 on 2024-12-25 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("commitfest", "0006_cfbot_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfbotbranch",
            name="needs_rebase_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patchhistory",
            name="by_cfbot",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="patchhistory",
            name="by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="patchhistory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("by_cfbot", True), ("by__isnull", True)),
                    models.Q(("by_cfbot", False), ("by__isnull", False)),
                    _connector="OR",
                ),
                name="check_by",
            ),
        ),
    ]
