# Generated by Django 4.2.19 on 2025-03-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0009_extra_branch_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfbotbranch",
            name="failing_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
