# Generated by Django 4.2.19 on 2025-06-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0010_add_failing_since_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitfest",
            name="draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="commitfest",
            name="status",
            field=models.IntegerField(
                choices=[(2, "Open"), (3, "In Progress"), (4, "Closed")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="commitfest",
            name="enddate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="commitfest",
            name="startdate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="patchoncommitfest",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Needs review"),
                    (2, "Waiting on Author"),
                    (3, "Ready for Committer"),
                    (4, "Committed"),
                    (5, "Moved to different CF"),
                    (6, "Rejected"),
                    (7, "Returned with feedback"),
                    (8, "Withdrawn"),
                ],
                default=1,
            ),
        ),
    ]
