# Generated by Django 4.2.19 on 2025-03-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0011_patch_status_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commitfest",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Future"),
                    (2, "Open"),
                    (3, "In Progress"),
                    (4, "Closed"),
                    (5, "Drafts"),
                ],
                default=1,
            ),
        ),
    ]
