# Generated by Django 4.2.19 on 2025-05-30 18:09

from django.db import migrations, models

import pgcommitfest.commitfest.models


def add_initial_tags(apps, schema_editor):
    Tag = apps.get_model("commitfest", "Tag")
    Tag.objects.bulk_create(
        [
            Tag(name="Bugfix", color="#a51d2d", description="Fixes a bug"),
            Tag(
                name="Backport",
                color="#1a5fb4",
                description="Once merged should be backported to old branches",
            ),
            Tag(
                name="Missing Tests",
                color="#c66424",
                description="Author should add tests",
            ),
            Tag(
                name="Missing Docs",
                color="#c66424",
                description="Author should add documentation",
            ),
            Tag(
                name="Missing Benchmarks",
                color="#c66424",
                description="Author should do additional benchmarks",
            ),
            Tag(
                name="Help - User Testing",
                color="#07732e",
                description="Reviewers are requested to try out the patch and provide user feedback on UX/UI",
            ),
            Tag(
                name="Help - Bikeshedding",
                color="#07732e",
                description="Reviewers are requested to propose or vote on stylistic changes like a user facing function name",
            ),
            Tag(
                name="Help - Docs",
                color="#07732e",
                description="Reviewers are requested to help review or write documentation",
            ),
            Tag(
                name="Help - Benchmarks",
                color="#07732e",
                description="Reviewers are requested to help discuss or do benchmarks and discuss performance impact",
            ),
            Tag(
                name="Good First Review",
                color="#613583",
                description="An easy to review patch for a new reviewer",
            ),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0012_add_status_related_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", pgcommitfest.commitfest.models.ColorField(max_length=7)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="patch",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="patches", to="commitfest.tag"
            ),
        ),
        migrations.RunPython(add_initial_tags, migrations.RunPython.noop),
    ]
