# Generated by Django 4.2.19 on 2025-05-30 18:09

from django.db import migrations, models

import pgcommitfest.commitfest.models


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0012_add_status_related_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", pgcommitfest.commitfest.models.ColorField(max_length=7)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="patch",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="patches", to="commitfest.tag"
            ),
        ),
    ]
