# Generated by Django 4.2.19 on 2025-05-30 18:09

from django.db import migrations, models

import pgcommitfest.commitfest.models


def add_initial_tags(apps, schema_editor):
    Tag = apps.get_model("commitfest", "Tag")
    Tag.objects.bulk_create(
        [
            Tag(name="Bugfix", color="#a51d2d", description="Fixes a bug"),
            Tag(
                name="Backport",
                color="#3d3846",
                description="Once merged should be backported to old branches",
            ),
            Tag(
                name="Missing Tests",
                color="#c66424",
                description="Author should add tests",
            ),
            Tag(
                name="Missing Docs",
                color="#c66424",
                description="Author should add documentation",
            ),
            Tag(
                name="Missing Benchmarks",
                color="#c66424",
                description="Author should do additional benchmarks",
            ),
            Tag(
                name="Help - User Testing",
                color="#07732e",
                description="Reviewers are requested to try out the patch and provide user feedback on UX/UI",
            ),
            Tag(
                name="Help - Bikeshedding",
                color="#07732e",
                description="Reviewers are requested to propose or vote on stylistic changes like a user facing function name",
            ),
            Tag(
                name="Help - Docs",
                color="#07732e",
                description="Reviewers are requested to help review or write documentation",
            ),
            Tag(
                name="Help - Benchmarks",
                color="#07732e",
                description="Reviewers are requested to help discuss or do benchmarks and discuss performance impact",
            ),
            Tag(
                name="Good First Review",
                color="#613583",
                description="An easy to review patch for a new reviewer",
            ),
            Tag(
                name="libpq",
                color="#1a5fb4",
                description="Makes significant libpq changes",
            ),
            Tag(
                name="psql",
                color="#1a5fb4",
                description="Makes significant psql changes",
            ),
            Tag(
                name="Performance",
                color="#1a5fb4",
                description="Improves performance",
            ),
            Tag(
                name="Logical Replication",
                color="#1a5fb4",
                description="Makes significant logical replication changes",
            ),
            Tag(
                name="Physical Replication",
                color="#1a5fb4",
                description="Makes significant physical replication changes",
            ),
            Tag(
                name="Refactoring Only",
                color="#1a5fb4",
                description="Only refactores code without changing functionality",
            ),
            Tag(
                name="Comments Only",
                color="#1a5fb4",
                description="Only updates code comments",
            ),
            Tag(
                name="Docs Only",
                color="#1a5fb4",
                description="Only updates user facing documentation",
            ),
            Tag(
                name="CI",
                color="#1a5fb4",
                description="Makes changes to the CI configuration or scripts",
            ),
            Tag(
                name="Testing",
                color="#1a5fb4",
                description="Adds/modifies tests or improves our testing frameworks",
            ),
            Tag(
                name="Monitoring",
                color="#1a5fb4",
                description="Adds new monitoring features or improves existing ones",
            ),
            Tag(
                name="GUC",
                color="#1a5fb4",
                description="Adds/modifies configuration parameters (GUCs)",
            ),
            Tag(
                name="PL/pgSQL",
                color="#1a5fb4",
                description="Involves changes to PL/pgSQL",
            ),
            Tag(
                name="PL/Python",
                color="#1a5fb4",
                description="Involves changes to PL/Python",
            ),
            Tag(
                name="PL/Perl",
                color="#1a5fb4",
                description="Involves changes to PL/Perl",
            ),
            Tag(
                name="PL/Tcl",
                color="#1a5fb4",
                description="Involves changes to PL/Perl",
            ),
            Tag(
                name="dblink",
                color="#1a5fb4",
                description="Involves changes to dblink",
            ),
            Tag(
                name="postgres_fdw",
                color="#1a5fb4",
                description="Involves changes to postgres_fdw",
            ),
            Tag(name="Security", color="#a51d2d", description="Improves security"),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0012_add_status_related_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", pgcommitfest.commitfest.models.ColorField(max_length=7)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="patch",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="patches", to="commitfest.tag"
            ),
        ),
        migrations.RunPython(add_initial_tags, migrations.RunPython.noop),
    ]
