# Generated by Django 4.2.19 on 2025-03-10 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0012_commitfest_status_draft"),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO commitfest_commitfest (id, name, status)
                                       VALUES (0, 'Drafts', 5);
        """),
    ]
