# Generated by Django 4.2.19 on 2025-07-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0013_tag_patch_tags"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TYPE cfbottask_status ADD VALUE 'PAUSED' AFTER 'CREATED';
            """
        ),
        migrations.AlterField(
            model_name="cfbottask",
            name="status",
            field=models.TextField(
                choices=[
                    ("CREATED", "Created"),
                    ("PAUSED", "Paused"),
                    ("NEEDS_APPROVAL", "Needs Approval"),
                    ("TRIGGERED", "Triggered"),
                    ("EXECUTING", "Executing"),
                    ("FAILED", "Failed"),
                    ("COMPLETED", "Completed"),
                    ("SCHEDULED", "Scheduled"),
                    ("ABORTED", "Aborted"),
                    ("ERRORED", "Errored"),
                ]
            ),
        ),
    ]
