# Generated by Django 4.2.19 on 2025-07-03 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0013_tag_patch_tags"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TYPE cfbottask_status ADD VALUE 'PAUSED' AFTER 'CREATED';
            """
        ),
    ]
