# Generated by Django 4.2.19 on 2025-08-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0014_add_paused_cfbot_task_state"),
    ]

    operations = [
        # Remove duplicate tasks keeping the one with the latest modified time
        migrations.RunSQL(
            """
            DELETE FROM commitfest_cfbottask
            WHERE id IN (
                SELECT id FROM (
                    SELECT id,
                           ROW_NUMBER() OVER (
                               PARTITION BY branch_id, position
                               ORDER BY modified DESC
                           ) as rn
                    FROM commitfest_cfbottask
                ) t
                WHERE rn > 1
            );
            """,
            reverse_sql="",
        ),
        # Remove unique constraint from task_id field
        migrations.AlterField(
            model_name="cfbottask",
            name="task_id",
            field=models.TextField(),
        ),
        # Add unique constraint on (branch_id, position)
        migrations.AddConstraint(
            model_name="cfbottask",
            constraint=models.UniqueConstraint(
                fields=["branch_id", "position"],
                name="commitfest_cfbottask_branch_position_unique",
            ),
        ),
    ]
