# Generated by Django 4.2.19 on 2025-08-07 17:25

from django.db import migrations


def create_missing_tags_and_map_topics(apps, schema_editor):
    """
    Create missing tags and map existing topics to appropriate tags.
    """
    Tag = apps.get_model("commitfest", "Tag")
    Patch = apps.get_model("commitfest", "Patch")
    Topic = apps.get_model("commitfest", "Topic")
    PatchTag = Patch.tags.through

    # Create missing tags
    Tag.objects.get_or_create(
        name="SQL Commands",
        defaults={
            "color": "#198754",
            "description": "SQL command implementation and enhancement",
        },
    )

    Tag.objects.get_or_create(
        name="System Administration",
        defaults={
            "color": "#495057",
            "description": "System administration and configuration",
        },
    )

    # Topic to Tag mapping
    topic_tag_mapping = {
        "Testing": "Testing",
        "Refactoring": "Refactoring Only",
        "Documentation": "Docs Only",
        "Code Comments": "Comments Only",
        "Bug Fixes": "Bugfix",
        "Performance": "Performance",
        "Security": "Security",
        "Monitoring & Control": "Monitoring",
        "Clients": "libpq",
        "SQL Commands": "SQL Commands",
        "System Administration": "System Administration",
        # 'Miscellaneous' and 'Server Features' are left untagged, because they
        # are too vague.
        # 'Procedural Languages' has no direct tag equivalent, because now
        # there are tags per language. So there's no clear tag that should be
        # chosen there. Similar for 'Replication & Recovery', which also has
        # separate tags now for logical and physical replication.
    }

    # Apply tags to existing patches based on their topics
    for topic_name, tag_name in topic_tag_mapping.items():
        try:
            topic = Topic.objects.get(topic=topic_name)
            tag = Tag.objects.get(name=tag_name)

            # Get all patch IDs with this topic
            patch_ids = list(
                Patch.objects.filter(topic=topic).values_list("id", flat=True)
            )

            # Bulk create the patch-tag relationships
            PatchTag.objects.bulk_create(
                [PatchTag(patch_id=pid, tag_id=tag.id) for pid in patch_ids],
                ignore_conflicts=True,
            )

            print(
                f"Mapped {len(patch_ids)} patches from topic '{topic_name}' to tag '{tag_name}'"
            )

        except Topic.DoesNotExist:
            print(f"Topic '{topic_name}' not found, skipping...")
        except Tag.DoesNotExist:
            print(f"Tag '{tag_name}' not found, skipping...")


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0015_cfbot_duplicate_task_fix"),
    ]

    operations = [
        migrations.RunPython(
            create_missing_tags_and_map_topics,
            migrations.RunPython.noop,
        ),
    ]
