# Generated by Django 4.2.19 on 2026-01-04 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0016_migrate_topics_to_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patch",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="commitfest.topic",
            ),
        ),
    ]
