# Generated by Django 4.2.19 on 2026-03-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0017_make_topic_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitfest",
            name="preclosure_warning_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
