# Generated by Django 5.2.12 on 2026-06-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0018_undo_pg19_final_close"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfbotbranch",
            name="build_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cfbottask",
            name="task_url",
            field=models.TextField(blank=True, null=True),
        ),
        # Backfill existing rows, which all predate cfbot sending these URLs
        # and thus are known to be Cirrus CI builds with deterministic URLs.
        migrations.RunSQL(
            """UPDATE commitfest_cfbotbranch
               SET build_url = 'https://cirrus-ci.com/github/postgresql-cfbot/postgresql/cf%2F' || patch_id""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """UPDATE commitfest_cfbottask
               SET task_url = 'https://cirrus-ci.com/task/' || task_id""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # The fields are added as nullable and only made NOT NULL here, after
        # the backfill has filled in all existing rows.
        migrations.AlterField(
            model_name="cfbotbranch",
            name="build_url",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="cfbottask",
            name="task_url",
            field=models.TextField(),
        ),
    ]
