# Generated by Django 5.2.12 on 2026-06-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0019_cfbot_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfbotbranch",
            name="build_url",
            field=models.TextField(blank=True, null=True),
        ),
        # Before this migration the ingest code stored an empty string when
        # cfbot didn't send a build_url, now it stores NULL. Convert the
        # already stored empty strings accordingly.
        migrations.RunSQL(
            "UPDATE commitfest_cfbotbranch SET build_url = NULL WHERE build_url = ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
