# Generated by Django 4.2.19 on 2025-03-04 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userprofile", "0003_emails_managed_upstream"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="show_relative_timestamps",
            field=models.BooleanField(
                default=True,
                verbose_name="Show relative timestamps throughout the site",
            ),
        ),
    ]
